#!/bin/bash

#############################################################################
# SSH Key Setup Script for Local Business Automizer Network
#
# This script automates:
# 1. SSH key generation
# 2. SSH config file setup
# 3. Public key distribution to network devices
#
# Usage: ./setup-ssh-keys.sh
#############################################################################

set -e  # Exit on error

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Configuration
SSH_DIR="$HOME/.ssh"
KEY_NAME="lba-network"
KEY_PATH="$SSH_DIR/$KEY_NAME"
SSH_CONFIG="$SSH_DIR/config"
COMMENT="lba-network@$(hostname)"

#############################################################################
# Functions
#############################################################################

print_header() {
    echo -e "\n${BLUE}=== $1 ===${NC}\n"
}

print_success() {
    echo -e "${GREEN}✓ $1${NC}"
}

print_error() {
    echo -e "${RED}✗ $1${NC}"
}

print_warning() {
    echo -e "${YELLOW}⚠ $1${NC}"
}

prompt_yes_no() {
    local prompt="$1"
    local response
    read -p "$(echo -e ${YELLOW}$prompt${NC}) (y/n): " response
    [[ "$response" == "y" || "$response" == "Y" ]]
}

#############################################################################
# Main Script
#############################################################################

clear

echo -e "${BLUE}"
cat << "EOF"
╔════════════════════════════════════════════════════════════════╗
║     SSH Key Setup for Local Business Automizer Network        ║
╚════════════════════════════════════════════════════════════════╝
EOF
echo -e "${NC}"

# Step 1: Check SSH directory
print_header "Step 1: Setting up SSH directory"

if [ ! -d "$SSH_DIR" ]; then
    mkdir -p "$SSH_DIR"
    chmod 700 "$SSH_DIR"
    print_success "Created SSH directory: $SSH_DIR"
else
    print_success "SSH directory exists: $SSH_DIR"
fi

# Step 2: Generate SSH keys
print_header "Step 2: SSH Key Generation"

if [ -f "$KEY_PATH" ]; then
    print_warning "Key already exists at $KEY_PATH"
    if prompt_yes_no "Generate new key anyway?"; then
        rm -f "$KEY_PATH" "$KEY_PATH.pub"
        print_success "Existing key removed"
    else
        print_warning "Skipping key generation"
        SKIP_KEY_GEN=true
    fi
fi

if [ "$SKIP_KEY_GEN" != "true" ]; then
    echo -e "\n${YELLOW}Generating Ed25519 SSH key...${NC}"
    ssh-keygen -t ed25519 -C "$COMMENT" -f "$KEY_PATH" -N ""
    print_success "SSH key generated"

    # Set proper permissions
    chmod 600 "$KEY_PATH"
    chmod 644 "$KEY_PATH.pub"
    print_success "Permissions set correctly"

    echo -e "\n${BLUE}Key fingerprint:${NC}"
    ssh-keygen -lf "$KEY_PATH.pub"
fi

# Step 3: Create/Update SSH Config
print_header "Step 3: Setting up SSH Config"

# Backup existing config
if [ -f "$SSH_CONFIG" ]; then
    cp "$SSH_CONFIG" "$SSH_CONFIG.backup.$(date +%s)"
    print_success "Backed up existing config"
fi

# Create new SSH config
cat > "$SSH_CONFIG.new" << 'SSHCONFIG'
# Local Business Automizer Network SSH Configuration
# Auto-generated by setup-ssh-keys.sh

# Zone3 Infrastructure

# Raspberry Pi 4 - Primary edge server
Host pi4
    HostName 192.168.1.100
    User pi
    IdentityFile ~/.ssh/lba-network
    Port 22
    StrictHostKeyChecking accept-new
    UserKnownHostsFile ~/.ssh/known_hosts
    ServerAliveInterval 60
    ServerAliveCountMax 3

# Gaming Rig - Local computing resource
Host gaming-rig
    HostName 192.168.1.101
    User localadmin
    IdentityFile ~/.ssh/lba-network
    Port 22
    StrictHostKeyChecking accept-new

# HP T640 Kiosk - Thin client terminal
Host hp-kiosk
    HostName 192.168.1.102
    User kiosk
    IdentityFile ~/.ssh/lba-network
    Port 22

# ThinK Center - Secondary workstation
Host thinkcenter
    HostName 192.168.1.103
    User admin
    IdentityFile ~/.ssh/lba-network
    Port 22

# NAS Backup - Network attached storage
Host nas-backup
    HostName 192.168.1.104
    User nas-admin
    IdentityFile ~/.ssh/lba-network
    Port 22

# Cloud Infrastructure

# Hetzner VPS - Primary cloud hosting
Host hetzner-vps
    # Replace [IP] with your actual Hetzner IP
    HostName 1.2.3.4
    User root
    IdentityFile ~/.ssh/lba-network
    Port 22

# Email Relay VPS
Host email-relay
    # Replace [IP] with your actual Email VPS IP
    HostName 5.6.7.8
    User deploy
    IdentityFile ~/.ssh/lba-network
    Port 22

# Tailscale Mesh Network Access

Host pi4-tailscale
    # Replace [TAILSCALE_IP] with Pi4's Tailscale IP
    HostName 100.0.0.1
    User pi
    IdentityFile ~/.ssh/lba-network
    StrictHostKeyChecking accept-new

# Default settings for all hosts
Host *
    AddKeysToAgent yes
    IdentitiesOnly yes
    LogLevel VERBOSE
    StrictHostKeyChecking accept-new
SSHCONFIG

# Merge with existing config if present
if [ -f "$SSH_CONFIG" ]; then
    # Check if our config already exists
    if grep -q "Local Business Automizer Network SSH Configuration" "$SSH_CONFIG"; then
        print_warning "SSH config already contains LBA configuration"
        if prompt_yes_no "Replace existing LBA config?"; then
            # Remove old LBA config (between markers)
            sed -i '/Local Business Automizer Network SSH Configuration/,/^$/d' "$SSH_CONFIG"
            cat "$SSH_CONFIG.new" >> "$SSH_CONFIG"
            rm "$SSH_CONFIG.new"
            print_success "SSH config updated"
        fi
    else
        cat "$SSH_CONFIG.new" >> "$SSH_CONFIG"
        rm "$SSH_CONFIG.new"
        print_success "SSH config merged"
    fi
else
    mv "$SSH_CONFIG.new" "$SSH_CONFIG"
    print_success "SSH config created"
fi

chmod 600 "$SSH_CONFIG"

# Step 4: Display next steps
print_header "Step 4: Next Steps"

echo -e "${YELLOW}Your public key:${NC}"
cat "$KEY_PATH.pub"

echo -e "\n${YELLOW}To add this key to a remote device, run:${NC}"
echo -e "${BLUE}ssh-copy-id -i $KEY_PATH user@hostname${NC}"

echo -e "\n${YELLOW}Or manually, on each remote device:${NC}"
echo -e "${BLUE}mkdir -p ~/.ssh${NC}"
echo -e "${BLUE}cat >> ~/.ssh/authorized_keys << 'EOF'${NC}"
cat "$KEY_PATH.pub"
echo -e "${BLUE}EOF${NC}"
echo -e "${BLUE}chmod 600 ~/.ssh/authorized_keys${NC}"

echo -e "\n${YELLOW}Quick SSH aliases (add to ~/.bashrc or ~/.zshrc):${NC}"
cat << 'ALIASES'
alias ssh-pi='ssh pi4'
alias ssh-gaming='ssh gaming-rig'
alias ssh-hetzner='ssh hetzner-vps'
alias ssh-mesh='ssh pi4-tailscale'
alias sync-nas='rsync -avz --delete pi4: nas-backup:'
ALIASES

# Step 5: Test connectivity
print_header "Step 5: Test Connectivity"

echo -e "${YELLOW}Available hosts in config:${NC}"
grep "^Host " "$SSH_CONFIG" | grep -v "^\*" | awk '{print "  - " $2}'

if prompt_yes_no "Test connection to a host?"; then
    read -p "Enter hostname (e.g., pi4): " test_host
    if grep -q "^Host $test_host" "$SSH_CONFIG"; then
        echo -e "\n${YELLOW}Testing connection to $test_host...${NC}"
        if ssh -o ConnectTimeout=5 "$test_host" "echo 'Connection successful'" 2>/dev/null; then
            print_success "Connection to $test_host successful!"
        else
            print_error "Connection to $test_host failed"
            echo -e "\n${YELLOW}Troubleshooting:${NC}"
            echo "1. Verify the host IP address in SSH config"
            echo "2. Check that the remote SSH server is running"
            echo "3. Ensure your public key is in ~/.ssh/authorized_keys on the remote"
        fi
    else
        print_error "Host $test_host not found in config"
    fi
fi

# Summary
print_header "Setup Complete!"

echo -e "${GREEN}Summary:${NC}"
echo "  ✓ SSH key generated: $KEY_PATH"
echo "  ✓ SSH config updated: $SSH_CONFIG"
echo "  ✓ Key permissions: 600"
echo ""
echo -e "${YELLOW}Next actions:${NC}"
echo "  1. Add your public key to each remote device"
echo "  2. Update IPs in SSH config (especially cloud VPS hosts)"
echo "  3. Test connections to each device"
echo "  4. Consider disabling password auth on remote servers"
echo ""
echo -e "${BLUE}For more information, see: infrastructure/SSH_SETUP.md${NC}"
echo ""
